# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='day',
            new_name='name',
        ),
    ]
