# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-22 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0002_auto_20181202_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(default='kek', max_length=30),
        ),
    ]
