# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-22 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0003_schedule_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(default='kek', max_length=10),
        ),
    ]
