# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdata',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
