# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20181202_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('para3', models.TextField()),
                ('para4', models.TextField()),
            ],
        ),
    ]
